name: weather_app_flutter_2_33
description: "A new Flutter project."
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ^3.5.1

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  geocoding: ^3.0.0
  geolocator: ^13.0.1
  get: ^4.6.6
  http: ^1.2.2
  intl: ^0.19.0
  sleek_circular_slider: ^2.0.1

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

flutter_launcher_icons:
  android: "launcher_icon"
  ios: "AppIcon"
  image_path: "assets/icons/weather-app.png"
  min_sdk_android: 21
  remove_alpha_ios: true

flutter:
  uses-material-design: true
  assets:
    - assets/icons/
    - assets/weather/
